// @ts-check

import { test, expect } from "@playwright/test";

test("test", async ({ page }) => {
  const takeScreenshot = async (name) => {
    await page.screenshot({ path: `screenshot/${name}.png` });
  };

  await page.goto("localhost:3000/lesson24/index.html");
  // await page.goto("http://127.0.0.1:3000/lesson24/index.html");
  // await page.getByRole("link", { name: "lesson24" }).click();
  await page.getByPlaceholder("Enter username").click();
  await page.getByPlaceholder("Enter username").press("Tab");
  await page.getByPlaceholder("Enter email").press("Tab");
  await page.getByPlaceholder("Enter password", { exact: true }).press("Tab");
  await page.getByPlaceholder("Enter password again").press("Tab");
  await page.getByRole("link", { name: "利用規約" }).press("Enter");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByLabel("利用規約", { exact: true }).press("ArrowDown");
  await page.getByText("利用規約を読み、同意しました", { exact: true }).click();
  await takeScreenshot("click agreeButton");
  await page.getByRole("button", { name: "Submit" }).click();
  await takeScreenshot("click submitButton");
});
